baseURL = "https://wiki.browniealice.net/"
languageCode = "ja-JP"
DefaultContentLanguage = "ja-jp"
title = "Alice in the Machine - wiki"
theme = "docdock"
publishDir = "docs"
footer = "true"

[outputs]
  home = [ "HTML", "RSS", "JSON"]

[[menu.shortcuts]]
  pre = "<h3>Links</h3>"
  identifier = "links"
[[menu.shortcuts]]
  name = "Blog"
  url = "https://blog.browniealice.net"
  weight = 30
  identifier = "blog"
[[menu.shortcuts]]
  name = "wiki"
  url = "https://wiki.browniealice.net"
  weight = 31
  identifier = "wiki"
[[menu.shortcuts]]
  name = "GitHub"
  url = "https://github.com/BrownieAlice/"
  weight = 32
  identifier = "github"
[[menu.shortcuts]]
  name = "Repo"
  url = "https://github.com/BrownieAlice/wiki.git"
  weight = 33
  identifier = "repo"

[taxonomies]
  category = "categories"
